name: Delete Old

on:
  workflow_dispatch:
  schedule:
    - cron: 3 2 12 * *

jobs:
  del_runs:
    runs-on: ubuntu-22.04
    steps:
    - name: Remove Workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0

    - name: Keep Recent
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 6
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}